# ida fish config

source /usr/share/cachyos-fish-config/cachyos-config.fish

# overwrite greeting
# potentially disabling fastfetch
function fish_greeting
    # smth smth
end

# Load autogenerated theme colors if present
if test -f ~/.config/fish/ida-theme.fish
    source ~/.config/fish/ida-theme.fish
end

# Improve readability of colored tools
if test -f ~/.config/fish/ida-git-colors.fish
    source ~/.config/fish/ida-git-colors.fish
end
