#!/usr/bin/env bash
# Wrapper script for ida-theme-watch
# This allows calling `ida-theme-watch` from PATH instead of using absolute paths in configs
exec "$(dirname "$(readlink -f "$0")")/theme/ida-theme-watch" "$@"
