#!/usr/bin/env bash
# Wrapper script for lyrics-tooltip.sh
# This allows calling `ida-lyrics-tooltip` from PATH instead of using absolute paths in configs
exec "$(dirname "$(readlink -f "$0")")/lyrics/lyrics-tooltip.sh" "$@"
