# AUTOGENERATED by wallust. Do not edit.
# Fish color settings for readable syntax highlighting.
#
# Uses "warning" as error color: color3.

# Base
set -Ux fish_color_normal {{foreground | strip}}
set -Ux fish_color_command {{foreground | strip}}
set -Ux fish_color_param {{foreground | strip}}
set -Ux fish_color_quote {{foreground | strip}}
set -Ux fish_color_operator {{foreground | strip}}
set -Ux fish_color_end {{foreground | strip}}

# Errors / unknown tokens (make it visible)
set -Ux fish_color_error {{color3 | strip}}

# Optional accents
set -Ux fish_color_comment {{color8 | strip}}
set -Ux fish_color_autosuggestion {{color8 | strip}}
