# AUTOGENERATED by wallust. Do not edit.
# Git colors for readable output.

# Use urgent for changes/untracked.
export IDA_GIT_COLOR_CHANGED="{{color1 | strip}}"
export IDA_GIT_COLOR_UNTRACKED="{{color1 | strip}}"

# Conservative defaults (keep branch green/red etc.)
# We only override file status foreground colors.
export GIT_CONFIG_PARAMETERS="${GIT_CONFIG_PARAMETERS:+$GIT_CONFIG_PARAMETERS }'color.status.changed=fg:#'"$IDA_GIT_COLOR_CHANGED"" 'color.status.untracked=fg:#'"$IDA_GIT_COLOR_UNTRACKED"""
