# AUTOGENERATED by wallust. Do not edit.
# Git colors for readable output using semantic colors.

# Git doesn't support truecolor (#RRGGBB) for status.* in all versions
# We use ANSI named colors as fallback
# The actual semantic colors are defined in ida-semantic.fish

# Load semantic colors if available
if test -f ~/.config/fish/ida-semantic.fish
    source ~/.config/fish/ida-semantic.fish
end

# Map semantic colors to ANSI colors for git
# These will be overridden by semantic values if available
set -gx IDA_GIT_COLOR_CHANGED "yellow"
set -gx IDA_GIT_COLOR_UNTRACKED "magenta"

# Use bright/bold versions for better visibility
function git --wraps git
    command git \
        -c "color.status.changed=bold yellow" \
        -c "color.status.untracked=bold magenta" \
        -c "color.status.added=bold green" \
        -c "color.status.updated=bold cyan" \
        $argv
end
