# AUTOGENERATED by wallust. Do not edit.
# Git colors for readable output.

# Always use a visible color for file status lines.
# Git does not support truecolor (#RRGGBB) for status.* in all versions; use named colors.
# We map "urgent" -> red.
set -gx IDA_GIT_COLOR_CHANGED magenta
set -gx IDA_GIT_COLOR_UNTRACKED yellow

function git --wraps git
    command git -c "color.status.changed=$IDA_GIT_COLOR_CHANGED" -c "color.status.untracked=$IDA_GIT_COLOR_UNTRACKED" $argv
end
